function secure(response) {
  const headers = new Headers(response.headers);
  headers.set("X-Content-Type-Options", "nosniff");
  headers.set("Referrer-Policy", "same-origin");
  headers.set("X-Frame-Options", "DENY");
  headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers
  });
}

export async function onRequest(context) {
  const url = new URL(context.request.url);
  const response = await context.next();

  // Preserve API responses exactly as generated by the endpoint.
  if (url.pathname.startsWith("/api/")) return response;

  const contentType = response.headers.get("Content-Type") || "";

  // Admin: force the native hidden state to win over component display rules.
  // Without this, .login-shell { display:grid } and .app-shell { display:grid }
  // override the browser's [hidden] rule, so the login remains visible after a
  // successful authentication even though JavaScript sets loginView.hidden=true.
  if ((url.pathname === "/adm" || url.pathname === "/adm/" || url.pathname === "/adm/index.html") && contentType.includes("text/html")) {
    const transformedAdmin = new HTMLRewriter()
      .on("head", {
        element(element) {
          element.append('<style id="admin-hidden-fix">[hidden]{display:none!important}</style>', { html: true });
        }
      })
      .transform(response);
    return secure(transformedAdmin);
  }

  if (url.pathname !== "/" && url.pathname !== "/index.html") return secure(response);
  if (!contentType.includes("text/html")) return secure(response);

  const transformed = new HTMLRewriter()
    .on('script[src="./assets/js/game-legacy.js"]', {
      element(element) { element.remove(); }
    })
    .on('script[src="/assets/js/game-legacy.js"]', {
      element(element) { element.remove(); }
    })
    .on("body", {
      element(element) {
        element.append('<script type="module" src="/assets/js/boot.js"></script>', { html: true });
      }
    })
    .transform(response);

  return secure(transformed);
}
